---
version: '3'
services:
  tor-client:
    image: 'nagev/tor'
    deploy:
      restart_policy:
        condition: on-failure

  polipo:
    image: 'clue/polipo'
    command: proxyAddress=0.0.0.0 proxyPort=8181 socksParentProxy=tor-client:9150
    deploy:
      restart_policy:
        condition: on-failure

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0'
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.type=single-node
    deploy:
      restart_policy:
        condition: on-failure
  kibana:
    image: 'docker.elastic.co/kibana/kibana-oss:7.7.0'
    ports:
      - "5601:5601"

  scrapy:
    build:
      context: ./scrapy
    environment:
      - elasticsearch=http://elasticsearch:9200
      - http_proxy=http://polipo:8181
      - https_proxy=http://polipo:8181
      - no_proxy=elasticsearch
      - urls=https://thehiddenwiki.org/
    deploy:
      restart_policy:
        condition: on-failure
